[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[start]
cmd = "cd backend && gunicorn app:app --bind 0.0.0.0:$PORT --log-level info"
